repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.630  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.1.1
    hooks:
    -   id: pylint
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: autopep8-wrapper
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: docs/generated/
    -   id: autopep8-wrapper
        args: ['--max-line-length=120', '--in-place']
    -   id: check-docstring-first
    -   id: double-quote-string-fixer
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^docs/source/conf.py$
    -   id: fix-encoding-pragma
        args: [--remove]
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: local
    hooks:
    -   id: no-catchall-except
        name: Prevent catchall except
        entry: except:$
        language: pygrep
        files: \.py$
